hystrix: 
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 600000

ribbon: 
  ReadTimeout: 600000000
  connection-timeout: 600000000
  eureka: 
    enabled: true      